package errors

import (
	"net/http"
)

var (
	NoEmail                   = NewError(http.StatusOK, "NO_EMAIL", "no email")
	NoEmailOrPhone            = NewError(http.StatusOK, "NO_EMAIL_OR_PHONE", "no email or phone")
	NoAddress                 = NewError(http.StatusOK, "NO_ADDRESS", "no address")
	NoAccountAddress          = NewError(http.StatusOK, "NO_ACCOUNT_ADDRESS", "no account address")
	AccountHadExisted         = NewError(http.StatusOK, "ACCOUNT_HAD_EXISTED", "Account had existed")
	AccountEmailExisted       = NewError(http.StatusOK, "ACCOUNT_EMAIL_EXISTED", "Account had bind email")
	EmailHadExisted           = NewError(http.StatusOK, "EMAIL_HAD_EXISTED", "Email had existed")
	EmailAlreadyBind          = NewError(http.StatusOK, "EMAIL_ALREADY_BIND", "Email already bind")
	PhoneAlreadyBind          = NewError(http.StatusOK, "EMAIL_ALREADY_BIND", "Phone already bind")
	PhoneHadExisted           = NewError(http.StatusOK, "PHONE_HAD_EXISTED", "Phone had existed")
	VerifyCodeError           = NewError(http.StatusOK, "VERIFY_CODE_ERROR", "Verify code error")
	SMSVerifyCodeError        = NewError(http.StatusOK, "SMS_VERIFY_CODE_ERROR", "SMS verify code error")
	EmailVerifyCodeError      = NewError(http.StatusOK, "EMAIL_VERIFY_CODE_ERROR", "Email Verify code error")
	NoPassword                = NewError(http.StatusOK, "NO_PASSWORD", "No password input")
	NoAssetPassword           = NewError(http.StatusOK, "NO_ASSET_PASSWORD", "No asset password input")
	AssetPasswordHadExisted   = NewError(http.StatusOK, "ASSET_PASSWORD_HAD_EXISTED", "Asset password had existed")
	InvalidEffectiveTime      = NewError(http.StatusOK, "INVALID_EFFECTIVE_TIME", "Invalid effective time")
	IncorretAccountOrPassword = NewError(http.StatusOK, "INCORRET_ACCOUNT_OR_PASSWORD", "Incorret account or password")
	IncorretPassword          = NewError(http.StatusOK, "INCORRET_PASSWORD", "Incorret password")
	IncorretAccountName       = NewError(http.StatusOK, "INCORRET_ACCOUNT_NAME", "Incorret account name")
	InvalidAddress            = NewError(http.StatusOK, "INVALID_ADDRESS", "Invalid address input")
	InvalidVerifyCodeType     = NewError(http.StatusOK, "INVALID_VERIFY_CODE_TYPE", "Invalid verify code type")
	NoVerifyCodeType          = NewError(http.StatusOK, "NO_VERIFY_CODE_TYPE", "no verify code type")
	AccountHadActived         = NewError(http.StatusOK, "ACCOUNT_HAD_ACTIVED", "Account had actived")
	AccountNotActived         = NewError(http.StatusOK, "ACCOUNT_NOT_ACTIVED", "Account not actived")
	AccountHadDisabled        = NewError(http.StatusOK, "ACCOUNT_HAD_DISABLE", "Account had disable")
	NoVerifyCode              = NewError(http.StatusOK, "NO_VERIFY_CODE", "No verify code")
	DisableSettle             = NewError(http.StatusOK, "DISABLE_SETTLE", "Disable deposit and withdraw now")
	InvalidCoinCode           = NewError(http.StatusOK, "INVALID_COIN_CODE", "Invalid coin code")
	RequestTooOfften          = NewError(http.StatusOK, "REQUEST_TOO_OFFTEN", "request too offen")
	InvalidEmailFormat        = NewError(http.StatusOK, "INVALID_EMAIL_FORMAT", "invalid email format")
	InvalidPhoneFormat        = NewError(http.StatusOK, "INVALID_PHONE_FORMAT", "invalid phone format")
	InvalidAccountType        = NewError(http.StatusOK, "INVALID_ACCOUNT_TYPE", "invalid account type")
	AddressNotFound           = NewError(http.StatusOK, "ADDRESS_NOT_FOUND", "address not found")
	GAKeyExpired              = NewError(http.StatusOK, "GAKEY_EXPIRED", "GAKey had expired")
	IncorretGACode            = NewError(http.StatusOK, "INCORRET_GACODE", "Incorret google authenticator code")
	GAKeyHadExisted           = NewError(http.StatusOK, "GAKEY_HAD_EXISTED", "You had bind google authenicator")
	WithdrawDisable           = NewError(http.StatusOK, "WITHDRAW_DISABLE", "Disable withdraw now")
	MaxLimitVolNoKYC          = NewError(http.StatusOK, "MAX_LIMIT_VOL_NO_KYC", "The Withdrawal amount exceeds limit, please complete the KYC authentication first.")
	MaxLimitCountTransfer     = NewError(http.StatusOK, "MAX_LIMIT_COUT_TRANSFER", "Transfer too often exceeds the limit, please try again later.")
	UidNotFound               = NewError(http.StatusOK, "UID_NOT_FOUND", "UID does not exist, please check again")
	AccountNameHadExisted     = NewError(http.StatusOK, "ACCOUNT_NAME_HAD_EXISTED", "")
	AccountNameTooLong        = NewError(http.StatusOK, "ACCOUNT_NAME_TOO_LONG", "")
	AccountNameInvalidSymbol  = NewError(http.StatusOK, "ACCOUNT_NAME_INVALID_SYMBOL", "")
	AccountNameHadBeenUsed    = NewError(http.StatusOK, "ACCOUNT_NAME_HAD_BEEN_USED", "")
	AccountSafeWarn           = NewError(http.StatusOK, "ACCOUNT_SAFE_WARN", "")
	NeedCaptch                = NewError(http.StatusOK, "NEED_CAPTCH", "")
	InvalidValidate           = NewError(http.StatusOK, "INVALID_VALIDATE", "")

	KYCAuthPassed     = NewError(http.StatusOK, "KYC_AUTH_PASSED", "You KYC auth had passed")
	KYCNoNationality  = NewError(http.StatusOK, "KYC_NO_NATIONALITY", "No nationality input")
	KYCNoFirstName    = NewError(http.StatusOK, "KYC_NO_FIRST_NAME", "No input first name")
	KYCNoLastName     = NewError(http.StatusOK, "KYC_NO_LAST_NAME", "No input last name")
	KYCNoIDType       = NewError(http.StatusOK, "KYC_NO_ID_TYPE", "No input ID type")
	KYCNoIDNo         = NewError(http.StatusOK, "KYC_NO_ID_NO", "No input ID no")
	KYCNoPhoto1       = NewError(http.StatusOK, "KYC_NO_PHOTO_1", "No photo of the front of the document")
	KYCNoPhoto2       = NewError(http.StatusOK, "KYC_NO_PHOTO_2", "No photo of the back of the document ")
	KYCNoPhoto3       = NewError(http.StatusOK, "KYC_NO_PHOTO_3", "No photo of the handheld of the document")
	KYCNotAllowUpdate = NewError(http.StatusOK, "KYC_NOT_ALLOW_UPDATE", "No allow update")
	KYCIDNoHadExisted = NewError(http.StatusOK, "KYC_ID_NO_HAD_EXISTED", "The ID number you submitted has been certified by another account. Please resubmit.")
	IllegalCharacter  = NewError(http.StatusOK, "ILLEGAL_CHAR", "Illegal character")
)
