package errors

import "net/http"

var (
	OTCOrderHadCanceled       = NewError(http.StatusOK, "OTC_ORDER_HAD_CANCELED", "")
	OTCOrderHadFinished       = NewError(http.StatusOK, "OTC_ORDER_HAD_FINISHED", "")
	OTCInventoryShortage      = NewError(http.StatusOK, "OTC_INVENTORY_SHORTAGE", "")
	OTCOrderNotOnWaitStatus   = NewError(http.StatusOK, "OTC_ORDER_NOT_ON_WAIT_SATUS", "")
	OTCGoodHadExisted         = NewError(http.StatusOK, "OTC_GOOD_HAD_EXISTED", "")
	OTCOrderNotAllowCancel    = NewError(http.StatusOK, "OTC_ORDER_NOT_ALLOW_CANCEL", "")
	OTCOrderNotAllowReceipt   = NewError(http.StatusOK, "OTC_ORDER_NOT_ALLOW_RECEIPT", "")
	OTCGoodNotFound           = NewError(http.StatusOK, "OTC_GOOD_NOT_FOUND", "")
	OTCGoodVolUpdated         = NewError(http.StatusOK, "OTC_GOOD_VOL_UPDATED", "")
	OTCInvalidBankOperate     = NewError(http.StatusOK, "OTC_INVALID_BANK_OPERATE", "")
	OTCNeedKYCRealName        = NewError(http.StatusOK, "OTC_NEED_KYC_REAL_NAME_BANK", "")
	OTCAccountNotFound        = NewError(http.StatusOK, "OTC_ACCOUNT_NOT_FOUND", "")
	OTCOrderIllegalOperation  = NewError(http.StatusOK, "OTC_ORDER_ILLEGAL_OPERATION", "")
	OTCOrderNotFound          = NewError(http.StatusOK, "OTC_ORDER_NOT_FOUND", "")
	OTCNoBankName             = NewError(http.StatusOK, "OTC_NO_BANK_NAME", "")
	OTCNoBankBranchName       = NewError(http.StatusOK, "OTC_NO_BANK_BRANCH_NAME", "")
	OTCNoBankAccountName      = NewError(http.StatusOK, "OTC_NO_BANK_ACCOUNT_NAME", "")
	OTCNoBankNumber           = NewError(http.StatusOK, "OTC_NO_BANK_NUMBER", "")
	OTCNoWeixinPayAccount     = NewError(http.StatusOK, "OTC_NO_WEIXIN_PAY_ACCOUNT", "")
	OTCNoWeixinPayAccountName = NewError(http.StatusOK, "OTC_NO_WEIXIN_PAY_ACCOUNT_NAME", "")
	OTCNoWeixinPayQR          = NewError(http.StatusOK, "OTC_NO_WEIXIN_PAY_QR", "")
	OTCNoAliPayAccount        = NewError(http.StatusOK, "OTC_NO_ALI_PAY_ACCOUNT", "")
	OTCNoAliPayAccountName    = NewError(http.StatusOK, "OTC_NO_ALI_PAY_ACCOUNT_NAME", "")
	OTCNoAliPayQR             = NewError(http.StatusOK, "OTC_NO_ALI_PAY_QR", "")
	OTCOrderB2CMinLimit       = NewError(http.StatusOK, "OTC_ORDER_B2C_MIN_LIMIT", "")
	OTCOrderB2CMaxLimit       = NewError(http.StatusOK, "OTC_ORDER_B2C_MAX_LIMIT", "")
	OTCOrderC2BMinLimit       = NewError(http.StatusOK, "OTC_ORDER_C2B_MIN_LIMI", "")
	OTCOrderC2BMaxLimit       = NewError(http.StatusOK, "OTC_ORDER_C2B_MAX_LIMI", "")
	OTCCoinSwitchClose        = NewError(http.StatusOK, "OTC_COIN_SWITCH_CLOSE", "")
	OTCGlobalSwitchClose      = NewError(http.StatusOK, "OTC_GLOBAL_SWITCH_CLOSE", "")
	OTCCancelOrderLimit       = NewError(http.StatusOK, "OTC_CANCEL_ORDER_LIMIT", "")
	OTCNoKYCDayMaxLimit       = NewError(http.StatusOK, "OTC_NO_KYC_DAY_MAX_LIMIT", "")
	OTCNoKYCSingleMaxLimit    = NewError(http.StatusOK, "OTC_NO_KYC_SINGLE_MAX_LIMIT", "")
	OTCNoReceiptInfo          = NewError(http.StatusOK, "OTC_NO_RECEIPT_INFO", "")
)
